[package]
name = "rust_radar_acc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.98"
bzip2 = { version = "0.5.2", features = ["libbz2-rs-sys"] }
